# Generated by Django 5.1.3 on 2024-11-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, verbose_name='Judul Film')),
                ('sinopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi')], max_length=20, verbose_name='Genre')),
                ('tanggal_rilis', models.DateField(verbose_name='Tanggal Rilis')),
                ('sutradara', models.CharField(max_length=50, verbose_name='Sutradara')),
                ('pemeran', models.TextField(blank=True, verbose_name='Daftar Pemeran')),
                ('poster', models.ImageField(upload_to='film/posters/', verbose_name='Poster Film')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Film-Film',
                'ordering': ['-tanggal_rilis'],
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengunjung', models.CharField(max_length=50, verbose_name='Nama Pengunjung')),
                ('isi_komentar', models.TextField(verbose_name='Isi Komentar')),
                ('tanggal_komentar', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Komentar')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='film.film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentar-Komenter',
                'ordering': ['-tanggal_komentar'],
            },
        ),
    ]
